export const EXAMPLE_TYPE_REQUEST = 'EXAMPLE_TYPE_REQUEST';
export const EXAMPLE_TYPE_SUCCESS = 'EXAMPLE_TYPE_SUCCESS';

// REDUX PERSIST
export const PERSIST_PERSIST = 'persist/PERSIST';
export const PERSIST_REHYDRATE = 'persist/REHYDRATE';

// Auth
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
// General auth failure
export const AUTH_FAILURE = 'AUTH_FAILURE';
