export const EXAMPLE_TYPE_REQUEST = 'EXAMPLE_TYPE_REQUEST';
export const EXAMPLE_TYPE_SUCCESS = 'EXAMPLE_TYPE_SUCCESS';

// REDUX PERSIST
export const PERSIST_PERSIST = 'persist/PERSIST';
export const PERSIST_REHYDRATE = 'persist/REHYDRATE';
